### ISSUE TITLE
🧮 Move deploy script onto GitHub Actions

### ISSUE THREAD

**Issue by leny** [becodeorg/oto#129]
We now have (_finally_) access to the GitHub Actions beta (had access on my personal account since a few months).

It will be more maintainable to move the deploy process onto it, less error-prone.

#### Notes

- To handle env file, we need to [encypt it and store it in the repository](https://help.github.com/en/articles/virtual-environments-for-github-actions#limits-for-secrets)
- There’s an [action for serverless](https://github.com/marketplace/actions/serverless)

### TODO

- ~~Encrypt env file and store it in the repo (put the _passphrase_ in 1password)~~
- [x] Remove _deploy-related_ scripts from `package.json` file
- [x] Write GitHub Action workflow with the following steps:
  - [x] Prepare npm env & install dependencies
  - [x] Create env file from secrets
  - [x] Build sources with babel
  - [x] Create release on Sentry
  - [x] Associate commits to release on Sentry
  - [x] Deploy to sls
  - [x] Inform Sentry for the release
